### ISSUE TITLE
chore: refactor workflows/axon-start-with-short-genesis.yml

### ISSUE THREAD

**Issue by Flouse** [axonweb3/axon#1322]
## Failed CI
https://github.com/axonweb3/axon/actions/runs/5865811220/job/15903430440

### Related PR
- https://github.com/axonweb3/axon/pull/1323

## TODOs for workflows/axon-start-with-short-genesis.yml

- [x] don't have to use [self-hosted runner](https://github.com/axonweb3/axon/blob/e6c4f6770073d7dc95d3075dd1ebd25481db0d6e/.github/workflows/axon-start-with-short-genesis.yml#L9)
- [x] (optional) don't push the test image to Docker Hub in this workflow
- [x] (optional) use health-check method of an Axon node, not [`grep from logs`](https://github.com/axonweb3/axon/blob/e6c4f6770073d7dc95d3075dd1ebd25481db0d6e/.github/workflows/axon-start-with-short-genesis.yml#L41C55-L41C59)

**Comment by chaoticlonghair** [comment]
The CI is broken again, and it's hard to test.

Because the CI will run with the workflow script in `HEAD` branch, not in my branch.

> To trigger the workflow_dispatch event, your workflow must be in the default branch.

Ref: [GitHub Docs: Configuring a workflow to run manually](https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow#configuring-a-workflow-to-run-manually)

So, the script is hard to test, and it could NOT update with the source codes.

The only way to test is: test after merged.

**Comment by Flouse** [comment]
> So, the script is hard to test, and it could NOT update with the source codes.

Do you think PR#1342 can fix the problem?
- https://github.com/axonweb3/axon/pull/1341
