### ISSUE TITLE
Tracking features for address encoding

### ISSUE THREAD

**Issue by chaoticlonghair** [axonweb3/axon#1343]
### Propose-a-new-feature

Address Encoding Features:

- [x] [EIP-55: Mixed-case checksum address encoding](https://eips.ethereum.org/EIPS/eip-55)

  - [x] APIs: axonweb3/axon#19 (ref: [sources code](https://github.com/axonweb3/axon/blob/1d89fa1c7004aaffeae404041e151d8b998a0a69/protocol/src/types/primitive.rs#L266-L281))

  - [x] Import from Cli: axonweb3/axon#1340

- [x] [EIP-155: Simple replay attack protection](https://eips.ethereum.org/EIPS/eip-155)

  jjy: Both EIP-155 and non-EIP-155 should be supported
  - If chain_id is added, it should be checked.
  - non-EIP-155 transactions are mainly to support EIP-1820. Many projects use this method to support multi-chain contracts using the same address.

~~- [ ] [EIP-1191: Add chain id to mixed-case checksum address encoding](https://eips.ethereum.org/EIPS/eip-1191)~~

  Support or not?

**Comment by KaoImin** [comment]
> * [EIP-1191: Add chain id to mixed-case checksum address encoding](https://eips.ethereum.org/EIPS/eip-1191)
>   Support or not?

The EIP-1191 is in the last call, consider supporting it after it becomes final.
