### ISSUE TITLE
Deprecate AXON_BOT_APP

### ISSUE THREAD

**Issue by Flouse** [axonweb3/axon#1390]
From https://github.com/axonweb3/axon/pull/1385, we can see that Axon may not need the [axon-bot](https://github.com/search?q=repo%3Aaxonweb3%2Faxon+AXON_BOT&type=code).

## TODO: try to clean and simplify the related workflows
- [x] refactor [.github/workflows/web3_compatible.yml](https://github.com/axonweb3/axon/blob/b0af286a2d7f4623965e3d711c3ffa9bf4d4600a/.github/workflows/web3_compatible.yml#L37) in https://github.com/axonweb3/axon/pull/1392
- [x] [.github/workflows/e2e_test.yml](https://github.com/axonweb3/axon/blob/b0af286a2d7f4623965e3d711c3ffa9bf4d4600a/.github/workflows/e2e_test.yml#L26)
- [x] [.github/workflows/v3_core_test.yml](https://github.com/axonweb3/axon/blob/b0af286a2d7f4623965e3d711c3ffa9bf4d4600a/.github/workflows/v3_core_test.yml#L34)
  https://github.com/axonweb3/axon/pull/1541
- [x] .github/workflows/openzeppelin_test*.yml
  https://github.com/axonweb3/axon/pull/1543
- [x] [.github/workflows/release.yml](https://github.com/axonweb3/axon/blob/b0af286a2d7f4623965e3d711c3ffa9bf4d4600a/.github/workflows/release.yml#L162)
  -> https://github.com/axonweb3/axon/pull/1635
- [x] [.github/workflows/chaos.yml](https://github.com/axonweb3/axon/blob/b0af286a2d7f4623965e3d711c3ffa9bf4d4600a/.github/workflows/chaos.yml#L21)
  -> https://github.com/axonweb3/axon/pull/1635

**Comment by Flouse** [comment]
AXON_BOT_APP has been disabled.
