### ISSUE TITLE
Tracking issue for code style, comments etc.

### ISSUE THREAD

**Issue by Flouse** [axonweb3/axon#1464]
_Note_: Tracking issues are meta-level issues meant to capture smaller tasks.

## Tasks

- [x] logger: https://github.com/axonweb3/axon/pull/1449#discussion_r1349822222 @KaoImin 
  fixed in https://github.com/axonweb3/axon/pull/1454
- [ ] https://github.com/axonweb3/axon/issues/1600
- [ ] With -D warnings argument for all cargo commands (especially clippy), [more bad codes](https://doc.rust-lang.org/rustc/lints/listing/warn-by-default.html) will be emerged.
   > In GitHub actions, just adding RUSTFLAGS: -D warnings to [global env section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#env) is enough to apply that.
- [ ] Track FIXME, TODO, XXX comments in code
